const http = require('http');
const fs = require('fs');
const path = require('path');
const PORT = process.env.PORT || 3000;
const doctorsFallback = [{id:1,name:'Dr. Ananya Sharma',specialty:'Cardiology'},{id:2,name:'Dr. Rahul Mehta',specialty:'General Medicine'},{id:3,name:'Dr. Priya Kapoor',specialty:'Dermatology'}];
const { issueOtp, verifyOtp, createToken, verifyToken, AuthError } = require('./auth');
const { getDb } = require('./db');
const { listDoctors, listAppointments, updateAppointmentStatus, createAppointment } = require('./repository');
const { listPrescriptions, createPrescription, listHealthRecords, createHealthRecord } = require('./phase3_repository');
const { listLabOrders, createLabOrder, updateLabOrderStatus } = require('./phase4_repository');
const { listPayments, getPaymentById, setProviderOrderId, createPayment, updatePaymentStatus } = require('./phase5_payment_repository');
const { createPaymentGatewayOrder } = require('./payment_gateway');
const { getWebhookSecret, verifyWebhookSignature, parseWebhookEvent } = require('./payment_webhook');
const { isAuthorizedPaymentStatusUpdate } = require('./payment_status_authorization');
const isAuthorizedAdmin = req => isAuthorizedPaymentStatusUpdate(req.headers, process.env.ADMIN_API_TOKEN || process.env.PAYMENT_STATUS_ADMIN_TOKEN);
const { validateCoordinates, emergencyResponse } = require('./phase6_emergency');
const { listNearbyHospitals } = require('./phase6_hospital_repository');
const { status: whatsappStatus, sendWhatsApp } = require('./whatsapp');

const configuredOrigins = (process.env.CORS_ALLOWED_ORIGINS || '').split(',').map(v => v.trim()).filter(Boolean);
const isAllowedOrigin = origin => !origin || configuredOrigins.includes('*') || configuredOrigins.includes(origin) || (process.env.NODE_ENV !== 'production' && /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin));
const send=(res,code,data,req)=>{const origin=req?.headers?.origin;if(isAllowedOrigin(origin)){res.setHeader('Access-Control-Allow-Origin',origin||'*');if(origin)res.setHeader('Vary','Origin');}res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization,X-Payment-Signature');res.writeHead(code,{'Content-Type':'application/json'});res.end(JSON.stringify(data));};
const parseBody=(req,done)=>{let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{done(null,JSON.parse(body||'{}'));}catch(e){done(e);}});};
const parseRawBody=(req,done)=>{let body='';req.setEncoding('utf8');req.on('data',c=>body+=c;);req.on('end',()=>done(null,body));req.on('error',done);};
const getAuthToken=(req)=>{const header=req.headers.authorization||'';return header.startsWith('Bearer ')?header.slice(7):null;};
const requireAuth=(req,res)=>{const payload=verifyToken(getAuthToken(req));if(!payload){send(res,401,{error:'Authentication required'},req);return null;}return payload;};
const server=http.createServer(async(req,res)=>{
  if(req.method==='OPTIONS') return send(res,204,{},req);
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  if(req.method==='GET' && (url.pathname==='/' || url.pathname.startsWith('/web/'))){
    const relative=url.pathname==='/'?'index.html':url.pathname.replace(/^\/web\//,'');
    const file=path.join(__dirname,'../../web',relative);
    if(file.startsWith(path.join(__dirname,'../../web')) && fs.existsSync(file) && fs.statSync(file).isFile()){
      const ext=path.extname(file).toLowerCase();
      const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json'};
      res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'}); return fs.createReadStream(file).pipe(res);
    }
  }
  if(url.pathname==='/api/notifications/whatsapp/status'&&req.method==='GET')return send(res,200,whatsappStatus(),req);
  if(url.pathname==='/api/notifications/whatsapp'&&req.method==='POST')return parseBody(req,async(err,data)=>{
    const auth=requireAuth(req,res); if(!auth)return;
    if(err)return send(res,400,{error:'Invalid JSON'},req);
    if(!data.to||!data.text||!data.event)return send(res,422,{error:'to, text and event are required'},req);
    return send(res,whatsappStatus().configured?200:503,await sendWhatsApp({to:data.to,text:data.text,event:data.event}),req);
  });
  if(url.pathname==='/health') return send(res,200,{ok:true,service:'Ayansha Health Care'},req);
  if(url.pathname==='/api/doctors'&&req.method==='GET'){try{const rows=await listDoctors();return send(res,200,rows||doctorsFallback,req);}catch(e){return send(res,503,{error:'Unable to load doctors'},req);}}
  if(url.pathname==='/api/db/health'&&req.method==='GET'){try{const db=await getDb();if(!db)return send(res,503,{ok:false,error:'DATABASE_URL not configured'},req);await db.query('SELECT 1');return send(res,200,{ok:true,database:'connected'},req);}catch(e){return send(res,503,{ok:false,error:'Database unavailable'},req);}}
  if(url.pathname==='/api/auth/request-otp'&&req.method==='POST')return parseBody(req,async(err,data)=>{if(err||!data.phone)return send(res,400,{error:'phone is required'},req);try{const result=await issueOtp(data.phone);return send(res,200,{message:'OTP sent',...result},req);}catch(e){if(e instanceof AuthError)return send(res,e.statusCode,{error:e.message},req);return send(res,502,{error:'Unable to send OTP'},req);}});
  if(url.pathname==='/api/auth/verify-otp'&&req.method==='POST')return parseBody(req,(err,data)=>{if(err||!data.phone||!data.otp)return send(res,400,{error:'phone and otp are required'},req);if(!verifyOtp(data.phone,String(data.otp)))return send(res,401,{error:'Invalid or expired OTP'},req);try{return send(res,200,{token:createToken(data.phone),user:{phone:data.phone}},req);}catch(e){if(e instanceof AuthError)return send(res,e.statusCode,{error:e.message},req);return send(res,503,{error:'Unable to create secure session'},req);}});
  if(url.pathname==='/api/emergency'&&req.method==='GET')return send(res,200,emergencyResponse(),req);
  if(url.pathname==='/api/hospitals/nearby'&&req.method==='GET'){try{const {latitude,longitude}=validateCoordinates(url.searchParams.get('latitude'),url.searchParams.get('longitude'));const rows=await listNearbyHospitals(latitude,longitude,url.searchParams.get('radiusKm')||25,url.searchParams.get('limit')||20);if(rows===null)return send(res,503,{error:'Hospital directory database is not configured'},req);return send(res,200,{latitude,longitude,radiusKm:Number(url.searchParams.get('radiusKm')||25),hospitals:rows},req);}catch(e){if(e.statusCode)return send(res,e.statusCode,{error:e.message},req);return send(res,503,{error:'Unable to load nearby hospitals'},req);}}
  if(url.pathname==='/api/appointments'&&req.method==='GET'){const auth=requireAuth(req,res);if(!auth)return;const requestedPhone=url.searchParams.get('phone');if(requestedPhone&&requestedPhone!==auth.sub)return send(res,403,{error:'Patient access denied'},req);try{const rows=await listAppointments(auth.sub);if(rows===null)return send(res,503,{error:'DATABASE_URL not configured'},req);return send(res,200,rows,req);}catch(e){return send(res,503,{error:'Unable to load appointments'},req);}}
  const statusMatch=url.pathname.match(/^\/api\/appointments\/(\d+)\/status$/);
  if(statusMatch&&req.method==='PATCH')return parseBody(req,async(err,data)=>{if(!isAuthorizedAdmin(req))return send(res,403,{error:'Admin authorization required'},req);if(err)return send(res,400,{error:'Invalid JSON'},req);try{const saved=await updateAppointmentStatus(Number(statusMatch[1]),data.status);if(saved)return send(res,200,saved,req);return send(res,503,{error:'DATABASE_URL not configured'},req);}catch(e){if(e.statusCode)return send(res,e.statusCode,{error:e.message},req);return send(res,503,{error:'Unable to update appointment status'},req);}});
  if(url.pathname==='/api/appointments'&&req.method==='POST')return parseBody(req,async(err,data)=>{const auth=requireAuth(req,res);if(!auth)return;if(err)return send(res,400,{error:'Invalid JSON'},req);if(!data.patientName||!data.phone||!data.doctorId||!data.appointmentAt)return send(res,422,{error:'patientName, phone, doctorId and appointmentAt are required'},req);if(data.phone!==auth.sub)return send(res,403,{error:'Patient access denied'},req);try{const saved=await createAppointment(data);if(saved)return send(res,201,saved,req);}catch(e){if(e.statusCode)return send(res,e.statusCode,{error:e.message},req);return send(res,503,{error:'Unable to save appointment'},req);}return send(res,503,{error:'DATABASE_URL not configured'},req);});
  if(url.pathname==='/api/prescriptions'&&req.method==='GET'){const auth=requireAuth(req,res);if(!auth)return;const phone=url.searchParams.get('phone');if(!phone)return send(res,422,{error:'phone is required'},req);if(phone!==auth.sub)return send(res,403,{error:'Patient access denied'},req);try{const rows=await listPrescriptions(phone);return send(res,200,rows||[],req);}catch(e){return send(res,503,{error:'Unable to load prescriptions'},req);}}
  if(url.pathname==='/api/prescriptions'&&req.method==='POST')return parseBody(req,async(err,data)=>{const auth=requireAuth(req,res);if(!auth)return;if(err)return send(res,400,{error:'Invalid JSON'},req);if(!data.phone||data.phone!==auth.sub)return send(res,403,{error:'Patient access denied'},req);try{const saved=await createPrescription(data);if(saved)return send(res,201,saved,req);return send(res,503,{error:'DATABASE_URL not configured'},req);}catch(e){if(e.statusCode)return send(res,e.statusCode,{error:e.message},req);return send(res,503,{error:'Unable to save prescription'},req);}});
  if(url.pathname==='/api/health-records'&&req.method==='GET'){const auth=requireAuth(req,res);if(!auth)return;const phone=url.searchParams.get('phone');if(!phone)return send(res,422,{error:'phone is required'},req);if(phone!==auth.sub)return send(res,403,{error:'Patient access denied'},req);try{const rows=await listHealthRecords(phone);return send(res,200,rows||[],req);}catch(e){return send(res,503,{error:'Unable to load health records'},req);}}
  if(url.pathname==='/api/health-records'&&req.method==='POST')return parseBody(req,async(err,data)=>{const auth=requireAuth(req,res);if(!auth)return;if(err)return send(res,400,{error:'Invalid JSON'},req);if(!data.phone||data.phone!==auth.sub)return send(res,403,{error:'Patient access denied'},req);try{const saved=await createHealthRecord(data);if(saved)return send(res,201,saved,req);return send(res,503,{error:'DATABASE_URL not configured'},req);}catch(e){if(e.statusCode)return send(res,e.statusCode,{error:e.message},req);return send(res,503,{error:'Unable to save health record'},req);}});
  if(url.pathname==='/api/lab-orders'&&req.method==='GET'){const auth=requireAuth(req,res);if(!auth)return;const phone=url.searchParams.get('phone');if(!phone)return send(res,422,{error:'phone is required'},req);if(phone!==auth.sub)return send(res,403,{error:'Patient access denied'},req);try{const rows=await listLabOrders(phone);return send(res,200,rows||[],req);}catch(e){return send(res,503,{error:'Unable to load lab orders'},req);}}
  if(url.pathname==='/api/lab-orders'&&req.method==='POST')return parseBody(req,async(err,data)=>{const auth=requireAuth(req,res);if(!auth)return;if(err)return send(res,400,{error:'Invalid JSON'},req);if(data.phone!==auth.sub)return send(res,403,{error:'Patient access denied'},req);try{const saved=await createLabOrder(data);if(saved)return send(res,201,saved,req);return send(res,503,{error:'DATABASE_URL not configured'},req);}catch(e){if(e.statusCode)return send(res,e.statusCode,{error:e.message},req);return send(res,503,{error:'Unable to save lab order'},req);}});
  const labStatusMatch=url.pathname.match(/^\/api\/lab-orders\/(\d+)\/status$/);
  if(labStatusMatch&&req.method==='PATCH')return parseBody(req,async(err,data)=>{if(!isAuthorizedAdmin(req))return send(res,403,{error:'Admin authorization required'},req);if(err)return send(res,400,{error:'Invalid JSON'},req);try{const saved=await updateLabOrderStatus(Number(labStatusMatch[1]),data.status);if(saved)return send(res,200,saved,req);return send(res,503,{error:'DATABASE_URL not configured'},req);}catch(e){if(e.statusCode)return send(res,e.statusCode,{error:e.message},req);return send(res,503,{error:'Unable to update lab order status'},req);}});
  if(url.pathname==='/api/payments'&&req.method==='GET'){const auth=requireAuth(req,res);if(!auth)return;const phone=url.searchParams.get('phone');if(!phone)return send(res,422,{error:'phone is required'},req);if(phone!==auth.sub)return send(res,403,{error:'Patient access denied'},req);try{const rows=await listPayments(phone);return send(res,200,rows||[],req);}catch(e){return send(res,503,{error:'Unable to load payments'},req);}}
  if(url.pathname==='/api/payments'&&req.method==='POST')return parseBody(req,async(err,data)=>{const auth=requireAuth(req,res);if(!auth)return;if(err)return send(res,400,{error:'Invalid JSON'},req);if(data.phone!==auth.sub)return send(res,403,{error:'Patient access denied'},req);try{const saved=await createPayment(data);if(saved)return send(res,201,saved,req);return send(res,503,{error:'DATABASE_URL not configured'},req);}catch(e){if(e.statusCode)return send(res,e.statusCode,{error:e.message},req);return send(res,503,{error:'Unable to create payment'},req);}});
  const paymentOrderMatch=url.pathname.match(/^\/api\/payments\/(\d+)\/order$/);
  if(paymentOrderMatch&&req.method==='POST')return parseBody(req,async(err,data)=>{const auth=requireAuth(req,res);if(!auth)return;if(err)return send(res,400,{error:'Invalid JSON'},req);if(!data.phone)return send(res,422,{error:'phone is required'},req);try{const payment=await getPaymentById(Number(paymentOrderMatch[1]));if(!payment)return send(res,404,{error:'Payment not found'},req);if(payment.phone!==auth.sub||payment.phone!==data.phone)return send(res,403,{error:'Payment does not belong to patient'},req);if(payment.provider_order_id)return send(res,200,{payment,order:{provider:payment.provider,orderId:payment.provider_order_id,amount:Math.round(Number(payment.amount)*100),currency:payment.currency}},req);const order=await createPaymentGatewayOrder({amount:payment.amount,currency:payment.currency,receipt:`payment_${payment.id}`});const saved=await setProviderOrderId(payment.id,order.provider,order.orderId);return send(res,200,{payment:saved,order:{provider:order.provider,orderId:order.orderId,amount:order.amount,currency:order.currency}},req);}catch(e){if(e.statusCode)return send(res,e.statusCode,{error:e.message},req);return send(res,502,{error:'Unable to create payment gateway order'},req);}});
  if(url.pathname==='/api/payments/webhook'&&req.method==='POST')return parseRawBody(req,async(err,rawBody)=>{if(err)return send(res,400,{error:'Unable to read webhook body'},req);const signature=req.headers['x-payment-signature'];if(!getWebhookSecret())return send(res,503,{error:'Payment webhook is not configured'},req);if(!verifyWebhookSignature(rawBody,signature))return send(res,401,{error:'Invalid webhook signature'},req);try{const event=parseWebhookEvent(rawBody);const paymentId=Number(event.paymentId);const status=event.status;if(!Number.isInteger(paymentId)||paymentId<1||typeof status!=='string')return send(res,422,{error:'paymentId and status are required'},req);const saved=await updatePaymentStatus(paymentId,status,event.providerPaymentId);if(saved)return send(res,200,{ok:true,payment:saved},req);return send(res,503,{error:'DATABASE_URL not configured'},req);}catch(e){if(e.statusCode)return send(res,e.statusCode,{error:e.message},req);return send(res,503,{error:'Unable to process payment webhook'},req);}});
  const paymentStatusMatch=url.pathname.match(/^\/api\/payments\/(\d+)\/status$/);
  if(paymentStatusMatch&&req.method==='PATCH')return parseBody(req,async(err,data)=>{if(err)return send(res,400,{error:'Invalid JSON'},req);if(!isAuthorizedPaymentStatusUpdate(req.headers))return send(res,403,{error:'Payment status update is restricted'},req);try{const saved=await updatePaymentStatus(Number(paymentStatusMatch[1]),data.status,data.providerPaymentId);if(saved)return send(res,200,saved,req);return send(res,503,{error:'DATABASE_URL not configured'},req);}catch(e){if(e.statusCode)return send(res,e.statusCode,{error:e.message},req);return send(res,503,{error:'Unable to update payment status'},req);}});
  send(res,404,{error:'Not found'},req);
});
server.listen(PORT,()=>console.log(`Ayansha API running on ${PORT}`));
