import 'package:flutter/material.dart';
import 'api_service.dart';

class LabBookingScreen extends StatefulWidget { const LabBookingScreen({super.key,required this.api}); final ApiService api; @override State<LabBookingScreen> createState()=>_LabBookingScreenState(); }
class _LabBookingScreenState extends State<LabBookingScreen>{final form=GlobalKey<FormState>();final test=TextEditingController();final notes=TextEditingController();bool submitting=false;
 Future<void> submit() async {if(!form.currentState!.validate())return;setState(()=>submitting=true);try{await widget.api.requestLabBooking(testName:test.text.trim(),notes:notes.text.trim());if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Lab booking request submitted. The lab will confirm availability.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}finally{if(mounted)setState(()=>submitting=false);}}
 @override void dispose(){test.dispose();notes.dispose();super.dispose();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Book Lab Test')),body:Form(key:form,child:ListView(padding:const EdgeInsets.all(20),children:[const Text('Lab test request',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('Submit your test request and the lab can confirm the available slot.'),const SizedBox(height:24),TextFormField(controller:test,decoration:const InputDecoration(labelText:'Test name',hintText:'e.g. CBC, Lipid Profile',border:OutlineInputBorder()),validator:(v)=>v==null||v.trim().isEmpty?'Enter a test name':null),const SizedBox(height:16),TextFormField(controller:notes,maxLines:4,decoration:const InputDecoration(labelText:'Notes (optional)',border:OutlineInputBorder())),const SizedBox(height:24),FilledButton.icon(onPressed:submitting?null:submit,icon:const Icon(Icons.science_outlined),label:Text(submitting?'Submitting...':'Submit lab request'))]));}
}
