import 'package:flutter/material.dart';
import 'api_service.dart';
import 'login_screen.dart';

void main() => runApp(const AyanshaHealthCareApp());

class AyanshaHealthCareApp extends StatefulWidget { const AyanshaHealthCareApp({super.key}); @override State<AyanshaHealthCareApp> createState()=>_AppState(); }
class _AppState extends State<AyanshaHealthCareApp>{ final api=ApiService(); bool authenticated=false; @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Ayansha Health Care',theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFF0E8F8F)),scaffoldBackgroundColor:const Color(0xFFF7FBFC)),home:authenticated?HomePage(api:api):LoginScreen(api:api,onVerified:()=>setState(()=>authenticated=true)));}

class HomePage extends StatefulWidget{const HomePage({super.key,required this.api});final ApiService api;@override State<HomePage> createState()=>_HomeState();}
class _HomeState extends State<HomePage>{int index=0;@override Widget build(BuildContext c){final pages=[HomeTab(api:widget.api),DoctorsTab(api:widget.api),BookingsTab(api:widget.api),RecordsTab(api:widget.api),const ProfileTab()];return Scaffold(body:pages[index],bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(i)=>setState(()=>index=i),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.medical_services_outlined),label:'Doctors'),NavigationDestination(icon:Icon(Icons.calendar_month_outlined),label:'Bookings'),NavigationDestination(icon:Icon(Icons.folder_outlined),label:'Records'),NavigationDestination(icon:Icon(Icons.person_outline),label:'Profile')]));}}

class HomeTab extends StatelessWidget{const HomeTab({super.key,required this.api});final ApiService api;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('AYANSHA HEALTH CARE',style:TextStyle(fontWeight:FontWeight.bold))),body:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:const Color(0xFF073C4A),borderRadius:BorderRadius.circular(24)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Welcome back 👋',style:TextStyle(color:Colors.white70)),SizedBox(height:8),Text('Your health, our priority.',style:TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.bold)),SizedBox(height:8),Text('Doctors, appointments and health records — all in one secure place.',style:TextStyle(color:Colors.white70))])),const SizedBox(height:22),const Text('What do you need today?',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:12),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.35,children:[_service(c,'Find a Doctor',Icons.medical_services,DoctorsTab(api:api)),_service(c,'Book Appointment',Icons.calendar_month,BookingPage(api:api)),_service(c,'Video Consultation',Icons.videocam,ConsultationPage(api:api)),_service(c,'Lab Tests',Icons.science,LabsPage(api:api)),_service(c,'Health Records',Icons.folder_shared,RecordsTab(api:api)),_service(c,'Emergency',Icons.emergency,EmergencyPage())]),const SizedBox(height:18),Card(child:ListTile(leading:const Icon(Icons.verified_user,color:Color(0xFF0E8F8F)),title:const Text('Care you can trust'),subtitle:const Text('Your health information should only be reviewed by you and your healthcare professionals.')))]));}
Widget _service(BuildContext c,String title,IconData icon,Widget page)=>Card(child:InkWell(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>page)),borderRadius:BorderRadius.circular(16),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,size:32,color:const Color(0xFF0E8F8F)),const Spacer(),Text(title,style:const TextStyle(fontWeight:FontWeight.w700))]))));}

class DoctorsTab extends StatefulWidget{const DoctorsTab({super.key,required this.api});final ApiService api;@override State<DoctorsTab> createState()=>_DoctorsState();}
class _DoctorsState extends State<DoctorsTab>{late Future<List<Map<String,dynamic>>> future;@override void initState(){super.initState();future=widget.api.listDoctors();}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Find a Doctor')),body:FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const Center(child:Text('Unable to load doctors.'));final ds=s.data??[];return ListView(padding:const EdgeInsets.all(16),children:ds.map((d)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text('${d['name']}'),subtitle:Text('${d['specialty']}'),trailing:FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>BookingPage(api:widget.api,doctorId:int.tryParse('${d['id']}'),doctorName:'${d['name']}'))),child:const Text('Book'))))).toList());}));}}

class BookingPage extends StatefulWidget{const BookingPage({super.key,required this.api,this.doctorId,this.doctorName});final ApiService api;final int? doctorId;final String? doctorName;@override State<BookingPage> createState()=>_BookingState();}
class _BookingState extends State<BookingPage>{DateTime? slot;String mode='Video';bool saving=false;final patient=TextEditingController();final phone=TextEditingController();Future<void>pick()async{final d=await showDatePicker(context:context,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:90)),initialDate:DateTime.now());if(d==null||!mounted)return;final t=await showTimePicker(context:context,initialTime:const TimeOfDay(hour:10,minute:0));if(t!=null)setState(()=>slot=DateTime(d.year,d.month,d.day,t.hour,t.minute));}Future<void>book()async{if(widget.doctorId==null||slot==null||patient.text.trim().isEmpty||phone.text.trim().isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Please complete patient, doctor and time details.')));return;}setState(()=>saving=true);try{await widget.api.createAppointment(patientName:patient.text.trim(),phone:phone.text.trim(),doctorId:widget.doctorId!,appointmentAt:slot!,mode:mode);if(mounted){await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Appointment Confirmed ✓'),content:Text('Your $mode appointment with ${widget.doctorName??'the doctor'} is confirmed.'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Done'))]);Navigator.pop(context,true);}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}finally{if(mounted)setState(()=>saving=false);}}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Book Appointment')),body:ListView(padding:const EdgeInsets.all(16),children:[Text(widget.doctorName??'Choose a doctor from Doctors',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:16),TextField(controller:patient,decoration:const InputDecoration(labelText:'Patient name',prefixIcon:Icon(Icons.person),border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Mobile number',prefixIcon:Icon(Icons.phone),border:OutlineInputBorder())),const SizedBox(height:12),OutlinedButton.icon(onPressed:pick,icon:const Icon(Icons.schedule),label:Text(slot==null?'Select date & time':'${slot!.day}/${slot!.month}/${slot!.year} • ${slot!.hour.toString().padLeft(2,'0')}:${slot!.minute.toString().padLeft(2,'0')}')),const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:mode,decoration:const InputDecoration(labelText:'Consultation mode',border:OutlineInputBorder()),items:const[DropdownMenuItem(value:'Video',child:Text('Video consultation')),DropdownMenuItem(value:'In-clinic',child:Text('In-clinic visit'))],onChanged:(v)=>setState(()=>mode=v!)),const SizedBox(height:22),FilledButton.icon(onPressed:saving?null:book,icon:const Icon(Icons.check_circle),label:Text(saving?'Confirming...':'Confirm Appointment'))]));@override void dispose(){patient.dispose();phone.dispose();super.dispose();}}

class BookingsTab extends StatelessWidget{const BookingsTab({super.key,required this.api});final ApiService api;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('My Bookings')),body:FutureBuilder<List<Map<String,dynamic>>>(future:api.listAppointments(),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const Center(child:Text('Unable to load bookings.'));final a=s.data??[];return ListView(padding:const EdgeInsets.all(16),children:[if(a.isEmpty)const Card(child:ListTile(title:Text('No appointments yet'),subtitle:Text('Book a consultation to see it here.'))),...a.map((x)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.calendar_today)),title:Text('Doctor #${x['doctorId']}'),subtitle:Text('${x['appointmentAt']} • ${x['mode']}'),trailing:Text('${x['status']??'confirmed'}')))),const SizedBox(height:12),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>BookingPage(api:api))),child:const Text('Book New Appointment'))]);}));}}

class RecordsTab extends StatelessWidget{const RecordsTab({super.key,required this.api});final ApiService api;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Health Records')),body:ListView(padding:const EdgeInsets.all(16),children:[_r('Prescriptions',Icons.medication,'Digital prescriptions from your consultations.'),_r('Lab Reports',Icons.science,'Test reports and results.'),_r('Medical History',Icons.history,'Your important health information.'),_r('Appointments',Icons.calendar_month,'Past and upcoming care.'),const SizedBox(height:12),const Text('Medical records are for information and care coordination. Always discuss results with a qualified healthcare professional.')]);}Widget _r(String t,IconData i,String s)=>Card(child:ListTile(leading:Icon(i,color:const Color(0xFF0E8F8F)),title:Text(t),subtitle:Text(s),trailing:const Icon(Icons.chevron_right)));}
class ProfileTab extends StatelessWidget{const ProfileTab({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('My Profile')),body:ListView(padding:const EdgeInsets.all(16),children:[const Center(child:CircleAvatar(radius:42,child:Icon(Icons.person,size:44))),const SizedBox(height:12),const Center(child:Text('Patient',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold))),const SizedBox(height:20),...['Personal Information','Family Members','Notifications','Privacy & Security'].map((x)=>Card(child:ListTile(title:Text(x),trailing:const Icon(Icons.chevron_right))))]));}
class ConsultationPage extends StatelessWidget{const ConsultationPage({super.key,required this.api});final ApiService api;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Video Consultation')),body:ListView(padding:const EdgeInsets.all(16),children:[const Card(child:ListTile(leading:Icon(Icons.videocam),title:Text('Secure video consultation'),subtitle:Text('Join only when your appointment is active.'))),FilledButton.icon(onPressed:(){},icon:const Icon(Icons.video_call),label:const Text('Join Consultation')),const SizedBox(height:12),const Text('Video service integration will be enabled with the production telehealth provider.')]);}
class LabsPage extends StatelessWidget{const LabsPage({super.key,required this.api});final ApiService api;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Lab Tests')),body:ListView(padding:const EdgeInsets.all(16),children:['Complete Blood Count','HbA1c / Diabetes','Lipid Profile','Thyroid Profile','Home Sample Collection'].map((x)=>Card(child:ListTile(leading:const Icon(Icons.science),title:Text(x),trailing:TextButton(onPressed:(){},child:const Text('Book'))))).toList()));}
class EmergencyPage extends StatelessWidget{const EmergencyPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Emergency Help')),body:Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.emergency,color:Colors.red,size:80),const SizedBox(height:18),const Text('For a life-threatening emergency, contact your local emergency service immediately.',textAlign:TextAlign.center,style:TextStyle(fontSize:17)),const SizedBox(height:20),FilledButton.icon(onPressed:(){},icon:const Icon(Icons.phone),label:const Text('Emergency Call'))])));}
