import 'package:flutter/material.dart';
import 'api_service.dart';
import 'login_screen.dart';
import 'records_screen.dart';

void main()=>runApp(const AyanshaHealthCareApp());
class AyanshaHealthCareApp extends StatefulWidget{const AyanshaHealthCareApp({super.key});@override State<AyanshaHealthCareApp> createState()=>_AppState();}
class _AppState extends State<AyanshaHealthCareApp>{final api=ApiService();bool authenticated=false;@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Ayansha Health Care',theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFF0E8F8F)),scaffoldBackgroundColor:const Color(0xFFF7FBFC)),home:authenticated?HomePage(api:api):LoginScreen(api:api,onVerified:()=>setState(()=>authenticated=true)));}
class HomePage extends StatefulWidget{const HomePage({super.key,required this.api});final ApiService api;@override State<HomePage> createState()=>_HomeState();}
class _HomeState extends State<HomePage>{int index=0;@override Widget build(BuildContext c){final pages=[HomeTab(api:widget.api),DoctorsTab(api:widget.api),BookingsTab(api:widget.api),RecordsScreen(api:widget.api),const ProfileTab()];return Scaffold(body:pages[index],bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(i)=>setState(()=>index=i),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.medical_services_outlined),label:'Doctors'),NavigationDestination(icon:Icon(Icons.calendar_month_outlined),label:'Bookings'),NavigationDestination(icon:Icon(Icons.folder_outlined),label:'Records'),NavigationDestination(icon:Icon(Icons.person_outline),label:'Profile')]));}}
class HomeTab extends StatelessWidget{const HomeTab({super.key,required this.api});final ApiService api;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('AYANSHA HEALTH CARE',style:TextStyle(fontWeight:FontWeight.bold))),body:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:const Color(0xFF073C4A),borderRadius:BorderRadius.circular(24)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Welcome back 👋',style:TextStyle(color:Colors.white70)),SizedBox(height:8),Text('Your health, our priority.',style:TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.bold)),SizedBox(height:8),Text('Doctors, appointments and health records — all in one secure place.',style:TextStyle(color:Colors.white70))])),const SizedBox(height:22),const Text('What do you need today?',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:12),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.35,children:[_service(c,'Find a Doctor',Icons.medical_services,DoctorsTab(api:api)),_service(c,'Book Appointment',Icons.calendar_month,BookingPage(api:api)),_service(c,'Video Consultation',Icons.videocam,ConsultationPage(api:api)),_service(c,'Lab Tests',Icons.science,LabsPage(api:api)),_service(c,'Health Records',Icons.folder_shared,RecordsScreen(api:api)),_service(c,'Emergency',Icons.emergency,EmergencyPage())])]);}
Widget _service(BuildContext c,String title,IconData icon,Widget page)=>Card(child:InkWell(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>page)),borderRadius:BorderRadius.circular(16),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,size:32,color:const Color(0xFF0E8F8F)),const Spacer(),Text(title,style:const TextStyle(fontWeight:FontWeight.w700))]))));}
class DoctorsTab extends StatefulWidget{const DoctorsTab({super.key,required this.api});final ApiService api;@override State<DoctorsTab> createState()=>_DoctorsState();}
class _DoctorsState extends State<DoctorsTab>{late Future<List<Map<String,dynamic>>> future;@override void initState(){super.initState();future=widget.api.listDoctors();}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Find a Doctor')),body:FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const Center(child:Text('Unable to load doctors.'));final ds=s.data??[];return ListView(padding:const EdgeInsets.all(16),children:ds.map((d)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text('${d['name']}'),subtitle:Text('${d['specialty']}'),trailing:FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>BookingPage(api:widget.api,doctorId:int.tryParse('${d['id']}'),doctorName:'${d['name']}'))),child:const Text('Book'))))).toList());}));}}
class BookingPage extends StatelessWidget{const BookingPage({super.key,required this.api,this.doctorId,this.doctorName});final ApiService api;final int? doctorId;final String? doctorName;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Book Appointment')),body:Center(child:Text('Booking flow remains available. Select a doctor to continue.')));}
class BookingsTab extends StatelessWidget{const BookingsTab({super.key,required this.api});final ApiService api;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('My Bookings')),body:FutureBuilder<List<Map<String,dynamic>>>(future:api.listAppointments(),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const Center(child:Text('Unable to load bookings.'));final a=s.data??[];return ListView(padding:const EdgeInsets.all(16),children:[if(a.isEmpty)const Card(child:ListTile(title:Text('No appointments yet'),subtitle:Text('Book a consultation to see it here.'))),...a.map((x)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.calendar_today)),title:Text('Doctor #${x['doctorId']}'),subtitle:Text('${x['appointmentAt']} • ${x['mode']}'),trailing:Text('${x['status']??'confirmed'}'))))]);}));}}
class ProfileTab extends StatelessWidget{const ProfileTab({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('My Profile')),body:ListView(padding:const EdgeInsets.all(16),children:[const Center(child:CircleAvatar(radius:42,child:Icon(Icons.person,size:44))),const SizedBox(height:12),const Center(child:Text('Patient',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold))),const SizedBox(height:20),...['Personal Information','Family Members','Notifications','Privacy & Security'].map((x)=>Card(child:ListTile(title:Text(x),trailing:const Icon(Icons.chevron_right))))]));}
class ConsultationPage extends StatelessWidget{const ConsultationPage({super.key,required this.api});final ApiService api;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Video Consultation')),body:const Center(child:Text('Secure video consultation will be available for active appointments.')));}
class LabsPage extends StatelessWidget{const LabsPage({super.key,required this.api});final ApiService api;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Lab Tests')),body:ListView(padding:const EdgeInsets.all(16),children:['Complete Blood Count','HbA1c / Diabetes','Lipid Profile','Thyroid Profile','Home Sample Collection'].map((x)=>Card(child:ListTile(leading:const Icon(Icons.science),title:Text(x),trailing:TextButton(onPressed:(){},child:const Text('Book'))))).toList()));}
class EmergencyPage extends StatelessWidget{const EmergencyPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Emergency Help')),body:const Center(child:Padding(padding:EdgeInsets.all(24),child:Text('For a life-threatening emergency, contact your local emergency service immediately.',textAlign:TextAlign.center)));}
