const API=window.AYANSH_API_URL||location.origin;const $=id=>document.getElementById(id);let doctors=[];const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Request failed');return d}
async function loadDoctors(){try{doctors=await api('/api/doctors');renderDoctors(doctors);$('doctorId').innerHTML='<option value="">Select doctor</option>'+doctors.map(d=>'<option value="'+d.id+'">'+esc(d.name)+' — '+esc(d.specialty)+'</option>').join('')}catch(e){$('doctorList').innerHTML='<div class="card">Unable to load doctors: '+esc(e.message)+'</div>'}}
function renderDoctors(list){$('doctorList').innerHTML=list.length?list.map(d=>'<article class="card"><p class="eyebrow">'+esc(d.specialty)+'</p><h3>'+esc(d.name)+'</h3><p class="muted">Consultation information follows the configured backend.</p><a class="primary" href="#appointment" onclick="selectDoctor('+d.id+')">Book Appointment</a></article>').join(''):'<div class="card">No doctors found.</div>'}
window.selectDoctor=id=>{$('doctorId').value=id;location.hash='appointment'};
$('doctorSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();renderDoctors(doctors.filter(d=>(d.name+' '+d.specialty).toLowerCase().includes(q)))});
$('appointmentForm').addEventListener('submit',async e=>{e.preventDefault();const out=$('appointmentResult');out.textContent='Booking…';try{const a=await api('/api/appointments',{method:'POST',body:JSON.stringify({patientName:$('patientName').value,phone:$('phone').value,doctorId:Number($('doctorId').value),appointmentAt:new Date($('appointmentAt').value).toISOString(),mode:$('mode').value})});out.innerHTML='<div class="result">Appointment confirmed. ID: '+esc(a.id)+' · Status: '+esc(a.status||'confirmed')+'<br>WhatsApp: '+esc(a.whatsapp?.status||'not requested')+'</div>'}catch(x){out.textContent=x.message}});
$('loadDashboard').onclick=async()=>{const p=encodeURIComponent($('dashboardPhone').value);if(!p)return;const g=$('dashboardGrid');g.innerHTML='<div class="loading">Loading…</div>';try{const [a,pr,h,l,pay]=await Promise.all([api('/api/appointments?phone='+p),api('/api/prescriptions?phone='+p),api('/api/health-records?phone='+p),api('/api/lab-orders?phone='+p),api('/api/payments?phone='+p)]);g.innerHTML=[['Appointments',a],['Prescriptions',pr],['Health Records',h],['Lab Orders',l],['Payments',pay]].map(([t,v])=>'<article class="card"><p class="eyebrow">'+t+'</p><h3>'+v.length+'</h3><p class="muted">Live API records loaded.</p></article>').join('')}catch(e){g.innerHTML='<div class="card">Dashboard load failed: '+esc(e.message)+'</div>'}};
$('aiBtn').onclick=()=>{const s=$('symptoms').value.trim();$('aiResult').textContent=s?'General guidance: monitor symptoms, rest and hydration where appropriate, and consider speaking with a qualified clinician. If symptoms are severe, sudden, or life-threatening, seek emergency care immediately.':'Please enter a symptom or question.'};
$('labForm').addEventListener('submit',async e=>{e.preventDefault();try{const r=await api('/api/lab-orders',{method:'POST',body:JSON.stringify({phone:$('labPhone').value,patientName:$('labPatient').value,testName:$('labName').value})});$('labResult').textContent='Lab order created: '+(r.id||'success')}catch(x){$('labResult').textContent=x.message}});
$('hospitalBtn').onclick=async()=>{try{const d=await api('/api/hospitals/nearby?latitude='+encodeURIComponent($('lat').value)+'&longitude='+encodeURIComponent($('lng').value));$('hospitalList').innerHTML=d.hospitals?.length?d.hospitals.map(h=>'<article class="card hospital"><h3>'+esc(h.name)+'</h3><p class="muted">'+esc(h.address||'')+'</p><p>'+esc(h.phone||'')+'</p></article>').join(''):'<div class="card">No hospitals returned.</div>'}catch(e){$('hospitalList').innerHTML='<div class="card">'+esc(e.message)+'</div>'}};
async function loadEmergency(){try{const d=await api('/api/emergency');$('emergencyText').textContent=d.message||'Emergency support information is available.';if(d.phone)$('callBtn').href='tel:'+d.phone}catch{}}
$('loginBtn').onclick=()=>{const phone=prompt('Enter phone number');if(!phone)return;api('/api/auth/request-otp',{method:'POST',body:JSON.stringify({phone})}).then(d=>{const otp=prompt('Development OTP: '+d.devOtp+'\nEnter OTP');return otp?api('/api/auth/verify-otp',{method:'POST',body:JSON.stringify({phone,otp})}):null}).then(d=>{if(d)alert('Login successful')}).catch(e=>alert(e.message))};
loadDoctors();loadEmergency();